apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: {{ .cname }}
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.25.7-k3s1
kubeAPI:
  hostIP: {{ .host_ip }}
  hostPort: "6443"
network: cilium
volumes:
  - volume: {{ .work_dir }}/bin/k3d-entrypoint-cilium.sh:/bin/k3d-entrypoint-cilium.sh
    nodeFilters:
    - all
options:
  k3d:
    wait: true
    timeout: "6m0s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
  k3s: # options passed on to K3s itself
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
        - server:*
      - arg: --disable=traefik
        nodeFilters:
        - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable=kube-proxy
        nodeFilters:
          - server:*
      - arg: --cluster-cidr={{ .cluster_subnet }}
        nodeFilters:
          - server:*
      - arg: --service-cidr={{ .service_subnet }}
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
